### ISSUE TITLE
Keywords not working

### ISSUE THREAD

**Issue by abdellatif-temsamani** [Juulsn/todo-issue#16]

**Comment by Juulsn** [comment]
Hi @abdellatif-temsamani 

could you provide more info about your problem?

Please attach your configuration and the code lines containing the comment you're trying to generate a GitHub issue from.

**Comment by abdellatif-temsamani** [comment]
hi @DerJuulsn, sorry for the late respond, yeah sure 
when i add keywords, the bot doesn't detect comments 

```yaml
---
name: Create issues from TODOs

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.
  push:
    branches:
      - develop

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Run Issue Bot
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: "^(node_modules/)"
          blobLines: 7
          blobLinesBefore: 2
          keywords: "FIXME,BUG,WONTFIX,TODO,WARN,HACK,PERF,OPTIM"
          reopenClosed: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
