### ISSUE TITLE
Import All not working

### ISSUE THREAD

**Issue by Stanzilla** [Juulsn/todo-issue#2]
Hey there! My config looks like this

```yml
name: Create issues for TODOs

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: "false"
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs.
  push:
    branches:
      - development

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Issue Bot
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: "^(mkdocs-material/|src/assets/javascripts/)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Yet, every time I want to kick off a manual run with import all, it errors with `Action can only be used on trigger push or in manual and importAll mode` any ideas?
